"""
Notifier — creates a GitHub Issue when new jobs are found.

Why GitHub Issues instead of Gmail SMTP:
  - Uses GITHUB_TOKEN which is already built into every Actions run (zero setup)
  - GitHub emails the repo owner automatically when an issue is opened
  - No App Passwords, no SMTP auth, nothing to expire or misconfigure
"""

import os
import requests
from datetime import datetime, timezone

# GITHUB_REPOSITORY is auto-set by GitHub Actions (e.g. "kakupepe09/job-alert-agent")
GITHUB_TOKEN      = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPOSITORY = os.environ.get("GITHUB_REPOSITORY", "")
ALERT_EMAIL       = "abumuazu09@gmail.com"   # kept for reference only


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _time_ago(posted_at_str: str) -> str:
    try:
        from dateutil import parser
        posted  = parser.parse(posted_at_str)
        if posted.tzinfo is None:
            posted = posted.replace(tzinfo=timezone.utc)
        diff    = datetime.now(timezone.utc) - posted
        minutes = int(diff.total_seconds() / 60)
        if minutes < 1:   return "just now"
        if minutes < 60:  return f"{minutes}m ago"
        return f"{minutes // 60}h ago"
    except Exception:
        return "recently"


def _create_issue(title: str, body: str, labels: list) -> None:
    if not GITHUB_TOKEN or not GITHUB_REPOSITORY:
        print("[Alert] No GITHUB_TOKEN/REPOSITORY — printing to stdout only")
        print(body)
        return

    # Ensure the label exists (silently ignore if it already does)
    for label in labels:
        try:
            requests.post(
                f"https://api.github.com/repos/{GITHUB_REPOSITORY}/labels",
                headers={"Authorization": f"token {GITHUB_TOKEN}",
                         "Accept": "application/vnd.github.v3+json"},
                json={"name": label, "color": "fbbf24"},
                timeout=8,
            )
        except Exception:
            pass

    resp = requests.post(
        f"https://api.github.com/repos/{GITHUB_REPOSITORY}/issues",
        headers={"Authorization": f"token {GITHUB_TOKEN}",
                 "Accept": "application/vnd.github.v3+json"},
        json={"title": title, "body": body, "labels": labels},
        timeout=10,
    )
    resp.raise_for_status()
    issue = resp.json()
    print(f"[Alert] Issue #{issue['number']} created → {issue['html_url']}")


# ─────────────────────────────────────────────────────────────────────────────
# Job alert
# ─────────────────────────────────────────────────────────────────────────────

def send_job_alert(jobs: list) -> None:
    if not jobs:
        return

    jobs    = sorted(jobs, key=lambda j: j.get("score", 0), reverse=True)
    count   = len(jobs)
    title   = f"🔥 {count} new React Native job{'s' if count > 1 else ''} — apply now"
    body    = _build_alert_md(jobs)
    _create_issue(title, body, ["job-alert"])
    print(f"[Alert] Job alert issued — {count} job(s)")


def _build_alert_md(jobs: list) -> str:
    lines = [
        "> **You're among the first to see these.** "
        "Most applicants won't spot them for another hour — apply immediately.\n"
    ]

    for i, job in enumerate(jobs[:20], 1):
        score      = job.get("score", 0)
        bar        = "🟢" if score >= 75 else "🟡" if score >= 55 else "⚪"
        time_ago   = _time_ago(job.get("posted_at", ""))
        salary_str = f" · 💰 {job['salary_text']}" if job.get("salary_text") else ""

        lines.append(f"---\n")
        lines.append(f"### {i}. [{job['title']} — {job['company']}]({job['url']})\n")
        lines.append(
            f"{bar} **{score}/100 match** &nbsp;·&nbsp; "
            f"⏰ {time_ago} &nbsp;·&nbsp; 📡 {job['source']}{salary_str}\n"
        )
        if job.get("description"):
            snippet = job["description"][:200].replace("\n", " ").strip()
            lines.append(f"> {snippet}…\n")

    lines.append("---")
    lines.append(
        f"\n*Generated by Job Alert Agent · "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*"
    )
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Daily digest (kept for future use)
# ─────────────────────────────────────────────────────────────────────────────

def send_daily_digest(cold_targets: list, recruiters: list) -> None:
    today = datetime.now().strftime("%A, %B %-d")
    title = f"📨 Daily digest — {today} · Cold targets + recruiter DMs"
    body  = _build_digest_md(cold_targets, recruiters, today)
    _create_issue(title, body, ["daily-digest"])
    print("[Alert] Daily digest issued")


def _build_digest_md(cold_targets: list, recruiters: list, today: str) -> str:
    lines = [f"# Your outreach targets for {today}\n"]

    lines.append("## 📨 Top 5 Companies — Cold Email Today\n")
    for i, t in enumerate(cold_targets[:5], 1):
        url_str = f" · [View →]({t['url']})" if t.get("url") else ""
        lines.append(f"**{i}. {t['name']}**{url_str}  \n{t['reason']}\n")

    lines.append("\n## 💬 Top 3 Recruiters — DM on LinkedIn\n")
    for i, r in enumerate(recruiters[:3], 1):
        li_str = f" · [LinkedIn]({r['linkedin']})" if r.get("linkedin") else ""
        lines.append(
            f"**{i}. {r['name']}** — {r['title']}{li_str}  \n{r['note']}\n"
        )

    lines.append(
        f"\n---\n*Daily digest · {today} · Job Alert Agent*"
    )
    return "\n".join(lines)
